@HOST = localhost:3000
@email = test@gmail.com

http://{{HOST}}

###

POST http://{{HOST}}
content-type: application/json

{
    "email": "{{email}}",
    "password": "123456"
}

###

http://{{HOST}}/analytics